name: HydraQueue
version: '0.5.6'
main: vadlox.dev.hydraQueue.HydraQueue
api-version: '1.21'
description: A Queue Plugin Similar To East's Queue Plugin.
website: vadlox.hydraquest.net

commands:
  queue:
    description: Queue up to be teleported with another player.
    usage: /queue
    aliases: [q]
  q:
    description: Queue up to be teleported with another player.
    usage: /q
  hydraqueue:
    description: HydraQueue main command.
    usage: /hydraqueue <subcommand>
    permission-message: You do not have permission to use this command.
